### PR TITLE
Project checklist

### LINKED ISSUE #11: End of the Project Checklist
- [x] Document multiple outputs in the README
- [x] Add QR Code to the README (maybe remove the current link)
- [x] Put the last commit on the original discussion: https://github.com/orgs/heig-vd-dai-course/discussions/397

Error Handling must be helpful
> The CLI displays a comprehensive help message on how to use the application and displays errors on invalid/missing inputs and/or processing errors
- [x] (Optional) Improve error handling by using a verbose flag to display the stacktrace, if not enabled a descriptive message will suffice

- [x] From the grading criteria, it seems that we must display the execution time of the program
> The CLI correctly processes the input file and writes the result in the output file with its execution time

### PR DESCRIPTION
**Pull request by A2va**
I'm opening this PR for discussion, consider it a draft

### CODE REVIEW

File: src/main/java/ch/heigvd/dai/commands/Root.java [hunk 1]
```diff
@@ -196,10 +209,18 @@ public String getText() {
...
 
+  public AvailableInputFormat getInputFormat() {
+    return inputFormat;
+  }
+
   public boolean isShow() {
     return show;
   }
 
+  public boolean isVerbose() {
```
Comment (A2va) [inline src/main/java/ch/heigvd/dai/commands/Root.java]: There are a lot of methods like this that are practically empty. I'm wondering if we could remove them, that might improve the readability. What do you think ?

**Comment by A2va** [comment]
The exception in the saveOutput method has not yet been handled by the ExceptionHelper.
https://github.com/A2va/dai-qr-code/blob/e56a75fa5d358b634dccf0c6a7a93ea07026901b/src/main/java/ch/heigvd/dai/commands/Root.java#L203-L235

File: src/main/java/ch/heigvd/dai/commands/Root.java (hunk 1 above)
Comment (Forestierr) [reply src/main/java/ch/heigvd/dai/commands/Root.java]: In our case, getters and setters are not really useful because we are in the same class.
In my opinion they can be removed.

**Review by Forestierr — APPROVED** [review]
All good for me.
